---
abstract: 'CyberSource backend for Business::OnlinePayment'
author:
  - 'Jad Wauthier <Jadrien dot Wauthier at GMail dot com>'
  - 'Caleb Cushing <xenoterracide@gmail.com>'
  - 'Peter Bowen <peter@bowenfamily.org>'
build_requires:
  Crypt::SSLeay: '0'
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  File::Spec::Functions: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  List::Util: '0'
  Test::More: '0'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Business-OnlinePayment-CyberSource
no_index:
  file:
    - perlcritic.rc
provides:
  Business::OnlinePayment::CyberSource:
    file: lib/Business/OnlinePayment/CyberSource.pm
    version: '3.000016'
  Business::OnlinePayment::CyberSource::Client:
    file: lib/Business/OnlinePayment/CyberSource/Client.pm
    version: '3.000016'
  Business::OnlinePayment::CyberSource::Role::ErrorReporting:
    file: lib/Business/OnlinePayment/CyberSource/Role/ErrorReporting.pm
    version: '3.000016'
  Business::OnlinePayment::CyberSource::Role::InputHandling:
    file: lib/Business/OnlinePayment/CyberSource/Role/InputHandling.pm
    version: '3.000016'
  Business::OnlinePayment::CyberSource::Role::TransactionHandling:
    file: lib/Business/OnlinePayment/CyberSource/Role/TransactionHandling.pm
    version: '3.000016'
requires:
  Business::CyberSource: '0.009000'
  Business::CyberSource::Client: '0.007006'
  Business::OnlinePayment: '3'
  DateTime: '0'
  Exception::Base: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::Aliases: '0'
  MooseX::NonMoose: '0'
  MooseX::StrictConstructor: '0'
  MooseX::Types::Common::String: '0'
  MooseX::Types::CyberSource: '0'
  MooseX::Types::Moose: '0'
  Try::Tiny: '0'
  namespace::autoclean: '0'
  perl: '5.010'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/xenoterracide/business-onlinepayment-cybersource/issues
  homepage: https://metacpan.org/dist/Business-OnlinePayment-CyberSource
  repository: git://github.com/xenoterracide/business-onlinepayment-cybersource.git
version: '3.000016'
x_contributors:
  - 'Jad Wauthier <jadrien.wauthier@gmail.com>'
  - 'Jad Wauthier <jwauthier@cpan.org>'
  - 'Jad Wauthier <jwauthier@hostgator.com>'
  - 'Peter A. Bowen <peter@bowenfamily.org>'
